export const mockBookData = [
  {
    id: 1,
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    category: "Classic",
    price: 10.99,
    stock: 50,
    status: "Available" as const,
    cover: "https://example.com/gatsby.jpg",
  },
  {
    id: 2,
    title: "1984",
    author: "George Orwell",
    category: "Dystopian",
    price: 8.99,
    stock: 30,
    status: "Available" as const,
    cover: "https://example.com/1984.jpg",
  },
  {
    id: 3,
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    category: "Classic",
    price: 12.50,
    stock: 0,
    status: "Out of Stock" as const,
    cover: "https://example.com/mockingbird.jpg",
  },
  {
    id: 4,
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    category: "Fantasy",
    price: 15.00,
    stock: 100,
    status: "Available" as const,
    cover: "https://example.com/hobbit.jpg",
  },
  {
    id: 5,
    title: "Harry Potter",
    author: "J.K. Rowling",
    category: "Fantasy",
    price: 20.00,
    stock: 10,
    status: "Discontinued" as const,
    cover: "https://example.com/hp.jpg",
  },
];
